spring:
  application:
    name: activityService
  mongodb:
    uri: mongodb://georgekibe:test1234@localhost:27017/fitness_application?authSource=admin
    database: fitness_application

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#rabbitmq:
#  exchange:
#    name: fitness.exchange
#  queue:
#    activity.queue
#  routing:
#    activity.tracking
#
rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking