spring.application.name=AuthProject

spring.security.oauth2.client.registration.oauth-project.client-id=oauth-project
spring.security.oauth2.client.registration.oauth-project.client-secret=Xo9E32k9w2VhLC6LGqsXSZN8ZV8AdC6u
spring.security.oauth2.client.registration.oauth-project.scope=openid, profile, roles, email
spring.security.oauth2.client.registration.oauth-project.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.oauth-project.redirect-uri=http://localhost:8080/login/oauth2/code/oauth-project
spring.security.oauth2.client.provider.oauth-project.issuer-uri=http://localhost:8443/realms/oauth2-demos