apiVersion: apps/v1
kind: Deployment
metadata:
  name: job
  labels:
    app: job
spec:
  replicas: 1
  template:
    metadata:
      name: job
      labels:
        app: job
    spec:
      containers:
      - name: job
        image: georgekibe/jobms:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
      restartPolicy: Always      
  selector:
    matchLabels:
      app: job  
