services:
  postgres_service:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: george
      POSTGRES_PASSWORD: kibe1234
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - microservices-network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - microservices-network
    restart: unless-stopped

  mongodb:
    image: mongo
    container_name: mongodb_container
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=george
      - MONGO_INITDB_ROOT_PASSWORD=kibe1234

  mongo-express:
      image: mongo-express
      container_name: mongo_express
      restart: unless-stopped
      ports:
        - 8081:8081
      environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=george
        - ME_CONFIG_MONGODB_ADMINPASSWORD=kibe1234
        - ME_CONFIG_MONGODB_SERVER=mongodb

  mail-dev:
    container_name: ms-mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025


networks:
  microservices-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo: