name: "PearlMaddison"

services:
  mongo:
    image: mongo:8
    container_name: mongodb
    ports:
#      - "127.0.0.1:27017:27017"
      - "27017:27017"
    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: georgekibe
      MONGO_INITDB_ROOT_PASSWORD: test1234
#    networks:
#      - app-network
    restart: on-failure
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP (app communication)
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: georgekibe
      RABBITMQ_DEFAULT_PASS: test1234
    restart: unless-stopped

volumes:
  mongo-data: