server:
  port: 8761
spring:
  application:
    name: discovery-service
  config:
    import: optional:configserver:http://localhost:8888

  main:
    banner-mode: off
logging:
  level:
    root: warn