spring.application.name=AuthProject

#keycloak
spring.security.oauth2.client.registration.keycloak-client.client-id=oauth2-client-credentials
spring.security.oauth2.client.registration.keycloak-client.client-secret=YxTBOsoMJqMxEm21zyWrN2KrkoxYkbbE
spring.security.oauth2.client.registration.keycloak-client.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.keycloak-client.scope=openid, profile, roles, email
spring.security.oauth2.client.provider.keycloak-client.token-uri=http://localhost:8443/realms/oauth2-demos/protocol/openid-connect/token

service2.url=http://localhost:8081

spring.security.oauth2.client.registration.oauth-project.client-id=oauth-project
spring.security.oauth2.client.registration.oauth-project.client-secret=Xo9E32k9w2VhLC6LGqsXSZN8ZV8AdC6u
spring.security.oauth2.client.registration.oauth-project.scope=openid, profile, roles, email
spring.security.oauth2.client.registration.oauth-project.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.oauth-project.redirect-uri=http://localhost:8080/login/oauth2/code/oauth-project
spring.security.oauth2.client.provider.oauth-project.issuer-uri=http://localhost:8443/realms/oauth2-demos